language: python
matrix:
  fast_finish: true
  allow_failures:
  - env: TOXENV=py36-djmaster
  - env: TOXENV=py37-djmaster
  - env: TOXENV=py38-djmaster
  - env: TOXENV=py39-djmaster
  include:
  - python: 3.6
    env: TOXENV=py36-djmaster
  - python: 3.7
    env: TOXENV=py37-djmaster
  - python: 3.8
    env: TOXENV=py38-djmaster
  - python: 3.9
    env: TOXENV=py39-djmaster
install:
- pip install tox
script:
- tox -e $TOXENV --verbose
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
before_script:
- psql -c 'create database pool;' -U postgres
- psql -c "CREATE USER pool WITH PASSWORD 'pool';" -U postgres
deploy:
  provider: pypi
  user: lcd1232
  password:
    secure: DRuUyoosZgtrdhkanHcxiCvo1ztuo+ge3Gn8EOiLA1TqQ6khTm4GTfBy2ot7bgEZtLI8cwUZH2Ee/PPGCgdnQ5ScriBWoPi3c+Wu/805X5VYTKsTOBycgv9v9mibzce4E5P7oK5MNYp6Zf06p98cPNiXzD3jvheUIWMI/0sZY2oE2GWd3k76Tm3qr2odZYhwf+51OdfvVcfp8DqpdK0SNPZT7WQDsnXViDImQJX+jxf0h9Le+Gd6f6vbiAk3eHhPxAp4gdVNX6NBFYIAyrc/qe3r1NAxa1Tk7iOzINgUvOKyQdqbP2akJwlQhUAllLXJmcA/xt0ty3zatIlyjHrtVOPP37iTCQUaWo0l4HSqEyBVpU7sV7P/kR7LRU6FjE0egvY8j/Jm4KMZ+hJtVmM1c0KH+5oPoWkh3wHfF3HpqDSVlTYbgQil+qsic6a1EyX2wt8KhSBroNBFsX6fYIOOzOAyMoLPYcJ0NsuD4KSAx2T0QdvGGbgtZsmz+wlInu5L95ewNcizvhBJE4r3a0kP/2j8HMUIQioLcMVn5kl0vXoVNEiLKxaHu+4jBY5E3tqRwEfumCXqBju1sO3MZhn3RkqyCozl1UXAOtmMEiu7Xfzt7VrMQnI1/LwJ/Ly2/e4r51t9zf+ASypkWLDawoyGSB9+40aWMxtSXQK/KMRLi2U=
  on:
    tags: true
